list_cols_df_verification = [
    "ID",
    "Period",
    "level_1_uid",
    "level_1_name",
    "level_2_uid",
    "level_2_name",
    "level_3_uid",
    "level_3_name",
    "level_4_uid",
    "level_4_name",
    "level_5_uid",
    "level_5_name",
    "level_6_uid",
    "level_6_name",
    "Risk category",
    "Is the center verified?",
    "Benefice complet VBR (if positive, VBR is beneficial) - period",
    "Subsidies based in declared values in the period",
    "Subsidies based in validated values in the period",
    "Subsidies based in declared values times the taux in the period",
    "Difference in subsidies declared vs validated in the period",
    "Difference in subsidies declared x taux vs validated in the period",
    "Median benefice complet VBR - window",
    "Median taux validation - window",
    "Median ecart - window",
]

list_cols_df_stats = [
    "Province",
    "Period",
    "Total number of centers",
    "Number of centers uneligible",
    "Number of centers high risk",
    "Number of centers middle risk",
    "Number of centers low risk",
    "Number of verified centers",
    "Cost of verification (VBR)",
    "cost of verification (syst)",
    "Subsidies (VBR)",
    "Subsidies (syst)",
    "Total cost (VBR)",
    "Total cost (syst)",
    "Ratio cost_verification cost_total (VBR)",
    "Ratio cost_verification cost_total (syst)",
    "Number of unverified centers where VBR saved money",
    "Number of unverified centers where VBR lost money",
    "Money saved by VBR (taking into account verif costs)",
]
list_cols_df_services = [
    "period",
    "level_5_uid",
    "Is the center not verified?",
    "Risk category",
    "Service name",
    "Taux of validation median",
    "Ecart median",
]
