list_cols_df_services = [
    "period",
    "ou_id",
    "Category of the center",
    "bool verified",
    "Risk category",
    "service",
    "Taux of validation",
    "Ecart median",
]

list_cols_df_verification = [
    "period",
    "ou_id",
    "level_2_uid",
    "level_2_name",
    "level_3_uid",
    "level_3_name",
    "level_4_uid",
    "level_4_name",
    "level_5_uid",
    "level_5_name",
    "level_6_uid",
    "level_6_name",
    "bool_verified",
    "diff_in_subsidies_decval_period",
    "diff_in_subsidies_tauxval_period",
    "benefice_complet_vbr",
    "taux_validation",
    "subside_dec_period",
    "subside_val_period",
    "subside_taux_period",
    "ecart_median_per_services",
    "ecart_median_general",
    "ecart_average_general",
    "categorie_risque",
    "high_risk_quality_indicators",
    "middle_risk_quality_indicators",
    "low_risk_quality_indicators",
    "nb_services_above_seuil",
    "nb_services",
]
