list_cols_df_verification = [
    "period",
    "ou_id",
    "level_2_uid",
    "level_2_name",
    "level_3_uid",
    "level_3_name",
    "level_4_uid",
    "level_4_name",
    "level_5_uid",
    "level_5_name",
    "level_6_uid",
    "level_6_name",
    "subside_dec_period",
    "subside_val_period",
    "subside_taux_period",
    "diff_in_subsidies_decval_period",
    "diff_in_subsidies_tauxval_period",
    "nb_services",
    "median_weighted_ecart",
    "nb_services_above_seuil_weighted_ecart",
    "median_dec_ver_ecart",
    "nb_services_above_seuil_dec_ver_ecart",
    "benefice_complet_vbr",
    "taux_validation",
    "categorie_risque_weighted_ecart",
    "categorie_risque_dec_ver_ecart",
    "categorie_risque_gain_verification",
    "categorie_risque",
    "bool_verified",
]

list_cols_df_stats = [
    "province",
    "periode",
    "total number of centres",
    "number of centers high risk",
    "number of centers middle risk",
    "number of centers low risk",
    "number of verified centers",
    "cost of verification (VBR)",
    "cost of verification (syst)",
    "subsidies (VBR)",
    "subsidies (syst)",
    "total cost (VBR)",
    "total cost (syst)",
    "ratio cost_verification cost_total (VBR)",
    "ratio cost_verification cost_total (syst)",
    "Number of centers where vbr was beneficial",
    "Number of centers over-subsidized",
    "Money saved by VBR (taking into account verif costs)",
    "Amount of over-subsidies",
    "Average of over-subsidies (non-verified centers)",
    "Average of over-subsidies (verified centers)",
]
